// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRecording() {
  return window['go']['main']['App']['CancelRecording']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CopyHistoryItem(arg1) {
  return window['go']['main']['App']['CopyHistoryItem'](arg1);
}

export function DeleteHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteHistoryItem'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function GetAudioData(arg1) {
  return window['go']['main']['App']['GetAudioData'](arg1);
}

export function GetAudioInputDevices() {
  return window['go']['main']['App']['GetAudioInputDevices']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentAudioInputDevice() {
  return window['go']['main']['App']['GetCurrentAudioInputDevice']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function IsModelDownloaded(arg1) {
  return window['go']['main']['App']['IsModelDownloaded'](arg1);
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetAudioInputDevice(arg1) {
  return window['go']['main']['App']['SetAudioInputDevice'](arg1);
}

export function SetAutoPaste(arg1) {
  return window['go']['main']['App']['SetAutoPaste'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetOpenAIKey(arg1) {
  return window['go']['main']['App']['SetOpenAIKey'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['main']['App']['SetProvider'](arg1);
}

export function SetTray(arg1) {
  return window['go']['main']['App']['SetTray'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function ToggleRecording() {
  return window['go']['main']['App']['ToggleRecording']();
}
