// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function CancelRecording():Promise<void>;

export function ClearHistory():Promise<void>;

export function CopyHistoryItem(arg1:string):Promise<void>;

export function DeleteHistoryItem(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function GetAudioData(arg1:string):Promise<string>;

export function GetAudioInputDevices():Promise<Array<main.AudioInputDevice>>;

export function GetConfig():Promise<models.Config>;

export function GetCurrentAudioInputDevice():Promise<string>;

export function GetHistory():Promise<Array<main.HistoryItem>>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetRecordingHotkey():Promise<string>;

export function GetRecordingHotkeyDisplayName():Promise<string>;

export function GetState():Promise<main.AppState>;

export function GetStats():Promise<main.UsageStats>;

export function Hide():Promise<void>;

export function IsModelDownloaded(arg1:string):Promise<boolean>;

export function Minimize():Promise<void>;

export function Quit():Promise<void>;

export function QuitApp():Promise<void>;

export function SetAudioInputDevice(arg1:string):Promise<void>;

export function SetAutoPaste(arg1:boolean):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetOpenAIKey(arg1:string):Promise<void>;

export function SetProvider(arg1:string):Promise<void>;

export function SetRecordingHotkey(arg1:string):Promise<void>;

export function SetSoundEnabled(arg1:boolean):Promise<void>;

export function SetTray(arg1:any):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;

export function ToggleRecording():Promise<void>;
